/*
  Extra credit: custom search UI on top of the Pagefind JS API.

  Pagefind's index is generated at build time (see the npm build script), so
  there is no search server: the browser lazily loads small index chunks from
  /pagefind/. The form ships hidden and is only revealed once the Pagefind
  module actually loads, so a user without JS (or on a broken build) never
  sees a dead search box — the <noscript> fallback links to browsable pages.

  Pagefind excerpts contain <mark> highlight tags. Rather than trusting that
  HTML string to innerHTML, we split on the mark tags and rebuild the excerpt
  from real text nodes and <mark> elements.
*/

const form = document.getElementById("search-form");
const input = document.getElementById("search-input");
const status = document.getElementById("search-status");
const resultsList = document.getElementById("search-results");

function excerptToNodes(excerpt) {
  const fragment = document.createDocumentFragment();
  // Split "a <mark>b</mark> c" into ["a ", "b", " c"]; odd indexes were marked.
  const parts = excerpt.split(/<\/?mark>/);
  parts.forEach((part, index) => {
    if (index % 2 === 1) {
      const mark = document.createElement("mark");
      mark.textContent = part;
      fragment.append(mark);
    } else {
      fragment.append(document.createTextNode(part));
    }
  });
  return fragment;
}

async function runSearch(pagefind, query) {
  status.textContent = "Searching…";
  resultsList.replaceChildren();

  const search = await pagefind.search(query);
  const results = await Promise.all(
    search.results.slice(0, 10).map((r) => r.data())
  );

  if (results.length === 0) {
    status.textContent = `No results for “${query}”.`;
    return;
  }

  for (const result of results) {
    const item = document.createElement("li");

    const heading = document.createElement("h2");
    const link = document.createElement("a");
    link.setAttribute("href", result.url);
    link.textContent = result.meta.title || result.url;
    heading.append(link);

    const excerpt = document.createElement("p");
    excerpt.append(excerptToNodes(result.excerpt));

    item.append(heading, excerpt);
    resultsList.append(item);
  }

  const label = results.length === 1 ? "result" : "results";
  status.textContent = `${results.length} ${label} for “${query}”.`;
}

async function init() {
  let pagefind;
  try {
    // Generated by `pagefind --site _site` during the build; not present in
    // source, which is why this import is computed at runtime.
    pagefind = await import("/pagefind/pagefind.js");
    await pagefind.init();
  } catch {
    status.textContent =
      "Search isn't available right now (the index may not have been built). " +
      "Use the navigation above to browse instead.";
    return;
  }

  form.addEventListener("submit", (event) => {
    event.preventDefault();
    const query = input.value.trim();
    if (query) {
      runSearch(pagefind, query);
    }
  });

  // Only reveal the form once search actually works.
  form.removeAttribute("hidden");
  input.focus();
}

init();
